name: preprocess
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - anndata=0.8.0
  - pandas=2.2.1
  - typeguard=4.1.5
  - pip
  - scikit-learn=1.3.0
  - joblib=1.2.0
  - networkx=3.1.0
  - quadprog=0.1.12
  - obonet=1.0.0
  - pip:
      - scanpy==1.9.8
