from snakemake.utils import min_version

min_version("7.30.1")


configfile: "config/config_deploy.yaml"


container: config["mambaforge_container_version"]


rule all:
    input:
        config["output_h5ad"],


rule decide_unknown_tissue:
    input:
        read_path=config["input_h5ad"],
        master_path=config["input_master"],
    output:
        save_path=config["output_h5ad"],
    params:
        master_tissue_column=config["master_tissue_column"],
        master_gene_column=config["master_gene_column"],
        deploy_decide_gene_column=config["deploy_decide_gene_column"],
        pca_n_components=config["pca_n_components"],
        seed=config["seed"],
    log:
        stdout=f'logs/decide_tissue/{config["organism"]}_{config["id"]}.stdout',
        stderr=f'logs/decide_tissue/{config["organism"]}_{config["id"]}.stderr',
    conda:
        "envs/train_model.yaml"
    shell:
        """
        export OMP_NUM_THREADS=1;
        export OPENBLAS_NUM_THREADS=1;
        export MKL_NUM_THREADS=1;
        export VECLIB_MAXIMUM_THREADS=1;
        export NUMEXPR_NUM_THREADS=1;
        python workflow/scripts/decide_tissue.py \
            --read_path {input.read_path} \
            --master_path {input.master_path} \
            --master_tissue_column {params.master_tissue_column} \
            --master_gene_column {params.master_gene_column} \
            --deploy_decide_gene_column {params.deploy_decide_gene_column} \
            --pca_n_components {params.pca_n_components} \
            --seed {params.seed} \
            --save_path {output.save_path} > {log.stdout} 2> {log.stderr}
        """
